Traceback (most recent call last):
  File "/Users/tsauter/venv/totoro/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/tsauter/venv/totoro/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/tsauter/venv/totoro/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/tsauter/venv/totoro/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/tsauter/venv/totoro/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/tsauter/venv/totoro/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/tsauter/venv/totoro/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
phi, dx, u, K, c, d = advection_diffusion(u=1.0, K=0.1, integration=0.05, dt=0.0028, Nx=40)
     
print('Dimensionless parameter c: {:.4f}'.format(c))
print('Dimensionless parameter d: {:.4f}'.format(d))

plt.figure(figsize=(12,5))
plt.plot(phi)
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m phi, dx, u, K, c, d [38;5;241m=[39m advection_diffusion(u[38;5;241m=[39m[38;5;241m1.0[39m, K[38;5;241m=[39m[38;5;241m0.1[39m, integration[38;5;241m=[39m[38;5;241m0.05[39m, dt[38;5;241m=[39m[38;5;241m0.0028[39m, Nx[38;5;241m=[39m[38;5;241m40[39m)
[0;32m----> 3[0m [38;5;28mprint[39m([38;5;124;43m'[39;49m[38;5;124;43mDimensionless parameter c: [39;49m[38;5;132;43;01m{:.4f}[39;49;00m[38;5;124;43m'[39;49m[38;5;241;43m.[39;49m[43mformat[49m[43m([49m[43mc[49m[43m)[49m)
[1;32m      4[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mDimensionless parameter d: [39m[38;5;132;01m{:.4f}[39;00m[38;5;124m'[39m[38;5;241m.[39mformat(d))
[1;32m      6[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m12[39m,[38;5;241m5[39m))

[0;31mTypeError[0m: unsupported format string passed to NoneType.__format__
TypeError: unsupported format string passed to NoneType.__format__

